In [ ]:
import gc
import torch
from transformers import pipeline

In [ ]:
chatbot = pipeline("text2text-generation", model="facebook/blenderbot-400M-distill")

message = "What is sport do you recommend in the winter?"
print(chatbot(message))


del chatbot
gc.collect()

In [ ]:
# 翻译

translation_bot = pipeline(task="translation", model="facebook/nllb-200-distilled-600M", torch_dtype=torch.float16)

text = """
Her panda is fridenly.
"""

print(translation_bot(text, src_lang="eng_Latn", tgt_lang="fra_Latn"))

del translation_bot
gc.collect()

In [ ]:
# 生成摘要

summarizer = pipeline(task="summarization", model="facebook/bart-large-cnn", torch_dtype=torch.float16)

text = """
The Hugging Face Hub is a platform with over 900k models, 200k datasets, and 300k demo apps (Spaces), all open source and publicly available, in an online platform where people can easily collaborate and build ML together. The Hub works as a central place where anyone can explore, experiment, collaborate, and build technology with Machine Learning. Are you ready to join the path towards open source Machine Learning?
"""

print(summarizer(text, min_length=5, max_length=20))

del summarizer
gc.collect()

In [4]:
# embedding

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

sentences1 = ['The cat sits outside', 'A man is playing guitar', 'The movies are awesome']
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
print(embeddings1)

sentences2 = ['The dog plays in the garden', 'A woman watches TV', 'The new movie is so great']
embeddings2 = model.encode(sentences1, convert_to_tensor=True)
print(embeddings2)

cosine_score = util.cos_sim(embeddings1, embeddings2)  # 余弦距离
print(cosine_score)

for i in range(len(cosine_score)):
    print(f'{sentences1[i]}\t\t{sentences2[i]}\t\tScore: {cosine_score[i][i]}')

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])
tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])
tensor([[ 1.0000,  0.0363, -0.0907],
        [ 0.0363,  1.0000, -0.0369],
        [-0.0907, -0.0369,  1.0000]])
The cat sits outside		The dog plays in the garden		Score: 1.0000001192092896
A man is playing guitar		A woman watches TV		Score: 1.0
The movies are awesome		The new movie is so great		Score: 1.0
